service:
  name: koyomi

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  logRetentionInDays:
    sandbox: "1"
  prune:
    automatic: true
    number: 3

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-prune-plugin

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, 'sandbox'} # Set the default stage used. Default is sandbox
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  logRetentionInDays: ${self:custom.logRetentionInDays.${opt:stage}}

functions:
  getUnreadPosts:
    handler: src/api.getUnreadPosts
    environment:
      SPREADSHEET_ID: ${ssm:/koyomi/${self:provider.stage}/SPREADSHEET_ID}
      CALENDAR_SHEET_NAME: ${ssm:/koyomi/${self:provider.stage}/CALENDAR_SHEET_NAME}
      GOOGLE_API_CREDENTIAL_JSON: ${ssm:/koyomi/${self:provider.stage}/GOOGLE_API_CREDENTIAL_JSON}
    events:
      - http:
          method: get
          path: posts/unread
